spring.servlet.multipart.file-size-threshold=1073741824
spring.servlet.multipart.location=/tmp
spring.servlet.multipart.max-file-size=1073741824
spring.servlet.multipart.max-request-size=1073741824
server.servlet.session.timeout=86400000
server.tomcat.max-http-post-size=1073741824
app.cookie.max.age=86400

server.port=8081
server.tomcat.max-threads=500
server.error.whitelabel.enabled=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
app.datasource.url=jdbc:postgresql://localhost:5432/demo
app.datasource.username=postgres
app.datasource.password=qwerty
app.datasource.max.connection=10
app.datasource.timeout.connection=60000
app.datasource.idle.min=0.3
app.datasource.idle.timeout=10000
app.datasource.max.lifetime=60000
app.datasource.batch.insert.size=10000

app.cors.mapping=/**
app.cors.origins=*
app.cors.methods=*
app.cors.headers=*

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/migration/db.changelog-master.xml
spring.liquibase.default-schema=public

app.deposit=*/30 * * * * ?
app.deposit.percent=10
app.deposit.max=207